### ISSUE TITLE
"Fix" changelogs.

### ISSUE THREAD

**Issue by jcgruenhage** [jcgruenhage/PlayMusicExporter#42]
Keeping the changelogs only at the github releases tab is imho a bad thing, so I'll add a CHANGELOG.MD file at some point, which will then be auto-generated by [clog](https://github.com/clog-tool/clog-cli), so commits from v0.9.7.0 (which will be the next release I guess) should follow the scheme that it uses.

**Comment by jcgruenhage** [comment]
## TODOs for this:
- [ ] Do proper semantic versioning, so MAJOR.MINOR.PATCH, not something like 0.9.6.0, that's a digit too much. Also, new features should cause a minor increment, not a patch increment, like what I did before..
- [ ] Write a .clog.toml containing a config.
- [ ] Write a changelog file for everything up to v0.10.0 (which will be the next release).
